[env]
QEMU = "qemu-system-riscv32"
TARGET = "riscv32imafc-unknown-none-elf"
BINARY_NAME = "egos-rs-xxxx"
BUILD_DIR = "target/${TARGET}/release"

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.objcopy]
dependencies = ["build"]
script = '''
rust-objcopy -O binary ${BUILD_DIR}/${BINARY_NAME} ${BUILD_DIR}/${BINARY_NAME}.bin
'''

[tasks.objdump]
dependencies = ["build"]
script = '''
rust-objdump --source --all-headers --demangle --line-numbers --wide ${BUILD_DIR}/${BINARY_NAME} > ${BUILD_DIR}/${BINARY_NAME}.lst
'''

[tasks.all]
dependencies = ["objcopy", "objdump"]

[tasks.qemu]
dependencies = ["all"]
script = '''
${QEMU} -nographic -machine virt -smp 1 -m 4M -bios ${BUILD_DIR}/${BINARY_NAME}.bin
'''

[tasks.clean]
command = "cargo"
args = ["clean"]
