[build]
target = "riscv32imafc-unknown-none-elf"

[target.riscv32imafc-unknown-none-elf]
linker = "riscv64-unknown-elf-gcc"
rustflags = [
    "-C", "link-arg=-T./linker/hello.lds",
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-march=rv32imafc",
    "-C", "link-arg=-mabi=ilp32f",
]
